// <auto-generated />
using System;
using AdessoRideShareRestApi.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AdessoRideShareRestApi.Migrations
{
    [DbContext(typeof(ContextService))]
    [Migration("20211121092634_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("AdessoRideShareRestApi.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdessoRideShareRestApi.Models.UserModel", b =>
                {
                    b.OwnsOne("System.Collections.Generic.List<AdessoRideShareRestApi.Models.TravelModel>", "Travel", b1 =>
                        {
                            b1.Property<Guid>("UserModelUserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer");

                            b1.HasKey("UserModelUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserModelUserId");
                        });

                    b.Navigation("Travel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
