// <auto-generated />
using System;
using AdessoRideShareRestApi.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AdessoRideShareRestApi.Migrations
{
    [DbContext(typeof(ContextService))]
    [Migration("20211121122052_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("AdessoRideShareRestApi.Models.PassengerModel", b =>
                {
                    b.Property<Guid>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TravelModelTravelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PassengerId");

                    b.HasIndex("TravelModelTravelId");

                    b.ToTable("PassengerModel");
                });

            modelBuilder.Entity("AdessoRideShareRestApi.Models.TravelModel", b =>
                {
                    b.Property<Guid>("TravelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EndCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("StartCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("TravelId");

                    b.ToTable("Travels");
                });

            modelBuilder.Entity("AdessoRideShareRestApi.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdessoRideShareRestApi.Models.PassengerModel", b =>
                {
                    b.HasOne("AdessoRideShareRestApi.Models.TravelModel", null)
                        .WithMany("Passengers")
                        .HasForeignKey("TravelModelTravelId");
                });

            modelBuilder.Entity("AdessoRideShareRestApi.Models.UserModel", b =>
                {
                    b.OwnsOne("System.Collections.Generic.List<AdessoRideShareRestApi.Models.TravelModel>", "Travel", b1 =>
                        {
                            b1.Property<Guid>("UserModelUserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer");

                            b1.HasKey("UserModelUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserModelUserId");
                        });

                    b.Navigation("Travel");
                });

            modelBuilder.Entity("AdessoRideShareRestApi.Models.TravelModel", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
